server:
 port: 0
spring:
 application:
  name : mbr-report-service
# Enabling H2 Console
 h2:
  console:
   enabled: true
   settings: 
    web-allow-others: true
 datasource:
  url: jdbc:h2:tcp://localhost:8888/mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: sa
 jpa: 
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
   ddl-auto: update
  show-sql: true
 zipkin: 
  base-url: http://localhost:9411/
logging:
 level:
  org: 
   #springframework: DEBUG
   com.capgemini.mbrt: DEBUG

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true
 instance:
  instance-id : ${spring.application.name}:${random.int}
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2
   
   