spring:
 application:
  name: mbr-gateway

server:
 port: 8001

eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
 instance:    instance-id: ${spring.application.name}:${server.port}
    
zuul:
  routes:
    mbr_service:
      path: /mbr/**
      serviceId: mbr-service
    mbr_report_service:
      path: /report/**
      serviceId: mbr-report-service   
# Increase the Hystrix timeout to 60s (globally)      
hystrix: 
 command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000      
