server:
 port: 8761

eureka:
 server:
  enable-self-preservation: false
 client:
  enabled:  true
  register-with-eureka: false
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka
  
spring:
 application:
  name: mbr-service-registry

